/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controllers.ControllerJugadorMesa;
import dominio.EstadisticasRondaJugador;
import dominio.Jugador;
import dominio.Mesa;
import dominio.Ronda;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


/**
 *
 * @author gcana
 */
public class VentanaJugadorMesa extends javax.swing.JFrame {

    private ControllerJugadorMesa controlador;
    
    
    public VentanaJugadorMesa(Mesa mesa, Jugador jugador) {
        initComponents();
        this.controlador = new ControllerJugadorMesa(this, mesa, jugador);
        this.mostrarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaldo = new javax.swing.JLabel();
        lblRuleta = new javax.swing.JLabel();
        lblRonda = new javax.swing.JLabel();
        lblNombreJugador = new javax.swing.JLabel();
        lblNumeroSorteado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lEstadisticas = new javax.swing.JList();
        btnApostar = new javax.swing.JButton();
        btnApostar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSaldo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSaldo.setText("lblSaldo");

        lblRuleta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblRuleta.setText("lblRuleta");

        lblRonda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblRonda.setText("lblRonda");

        lblNombreJugador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreJugador.setText("lblNombreJugador");

        lblNumeroSorteado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNumeroSorteado.setText("lblNumeroSorteado");

        lEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lEstadisticas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lEstadisticas.setToolTipText("");
        jScrollPane1.setViewportView(lEstadisticas);

        btnApostar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnApostar.setText("Apostar 50 al 30");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        btnApostar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnApostar1.setText("Apostar 100 al 23");
        btnApostar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostar1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Ronda | Total apostado | Ganado | Perdido | Balance");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNumeroSorteado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblRuleta)
                        .addGap(5, 5, 5)
                        .addComponent(lblRonda)
                        .addGap(112, 275, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSaldo)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 168, Short.MAX_VALUE)
                                .addComponent(lblNombreJugador))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApostar1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(lblRuleta)
                    .addComponent(lblRonda)
                    .addComponent(lblNombreJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroSorteado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApostar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApostar1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        controlador.getMesa().setApuesta(controlador.getJugador(), 50, 30);
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnApostar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostar1ActionPerformed
        controlador.getMesa().setApuesta(controlador.getJugador(), 100, 23);
    }//GEN-LAST:event_btnApostar1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnApostar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lEstadisticas;
    private javax.swing.JLabel lblNombreJugador;
    private javax.swing.JLabel lblNumeroSorteado;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JLabel lblRuleta;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables

    public void mostrarInfo() {
    //Muestra:
    //El saldo del jugador (este valor es el mismo en todas las mesas a las que
    //el jugador se haya unido);
    int saldoJugador = controlador.getJugador().getSaldo();
    lblSaldo.setText("Saldo: $" + saldoJugador);
    
    //El número de mesa de ruleta y
    int numeroMesa = controlador.getMesa().getId();
    lblRuleta.setText("Ruleta #" + numeroMesa);
    
    //de ronda actual;
    int numeroRonda = controlador.getMesa().getRondas().size();
    lblRonda.setText("Ronda #" + numeroRonda);
    
    //El nombre completo del jugador;
    String nombreJugador = controlador.getJugador().getNombre();
    lblNombreJugador.setText(nombreJugador);
    
    //El numero sorteado en la ultima ronda
    Mesa mesa = controlador.getMesa();
    Ronda ultimaRonda = mesa.getRondas().get(mesa.getRondas().size() - 1);
    int numeroSorteado = ultimaRonda.getNumeroSorteado();
    lblNumeroSorteado.setText("Numero sorteado: " + numeroSorteado);
    
    //La mesa con las apuestas del jugador (inicialmente vacío);
    
    
    
    
         
        
    }
    

    public void mostrarInfoEstadisticas(){
        //La lista de rondas en las que el jugador ha participado, con los siguientes
        //datos: Numero de ronda, Monto total apostado en la ronda, Monto total
        //ganado en la ronda, Monto total perdido en la ronda, balance de la ronda
        //(diferencia entre ganado y perdido).
        DefaultListModel<String> modelo = new DefaultListModel<>();
        ArrayList<EstadisticasRondaJugador> estadisticas = controlador.getMesa().getUltimasEstadisticas(controlador.getJugador(), 5);
        for(EstadisticasRondaJugador estadistica: estadisticas){
            String devolucion = "#" + estadistica.getRonda().getId() + " | " + estadistica.getTotalApostado() + " | " + estadistica.getGanado() + " | " + estadistica.getPerdido() + " | " + estadistica.getBalance();
            modelo.addElement(devolucion);
        }
        lEstadisticas.setModel(modelo);
        
    }
    
    
}
