/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controllers.ControllerCrupier;
import dominio.Crupier;
import dominio.Jugador;
import dominio.Mesa;
import dominio.Ronda;
import dominio.Sesion;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author gcana
 */
public class VentanaCrupier extends javax.swing.JFrame {

    private ControllerCrupier controlador;
    /**
     * Creates new form VentanaCrupier
     */
    public VentanaCrupier(Crupier crupier) {
        initComponents();
        this.controlador = new ControllerCrupier(this, crupier);
        this.setTitle("Bienvenido " + crupier.getNombre());
        this.mostrarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRonda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lJugadoresUnidos = new javax.swing.JList<>();
        lblBalance = new javax.swing.JLabel();
        lblApuestas = new javax.swing.JLabel();
        btnLanzar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaUltimosLanzamientos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        labelNumeroRuleta = new javax.swing.JLabel();
        labelRonda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lJugadoresUnidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lJugadoresUnidos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(lJugadoresUnidos);

        lblBalance.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblBalance.setText("lblBalance");

        lblApuestas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblApuestas.setText("lblApuestas");

        btnLanzar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLanzar.setText("Lanzar / Pagar");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });

        listaUltimosLanzamientos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(listaUltimosLanzamientos);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Jugador | Saldo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNumeroRuleta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelNumeroRuleta.setText("labelNumeroRuleta");

        labelRonda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelRonda.setText("labelRonda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lblRonda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(labelNumeroRuleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRonda)
                        .addGap(57, 57, 57)
                        .addComponent(btnLanzar)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApuestas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRonda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroRuleta)
                    .addComponent(lblBalance)
                    .addComponent(btnLanzar)
                    .addComponent(labelRonda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblApuestas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        controlador.getCrupier().getMesaAsignada().nuevaRonda();

    }//GEN-LAST:event_btnLanzarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lJugadoresUnidos;
    private javax.swing.JLabel labelNumeroRuleta;
    private javax.swing.JLabel labelRonda;
    private javax.swing.JLabel lblApuestas;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JList<String> listaUltimosLanzamientos;
    // End of variables declaration//GEN-END:variables

    public void cambioEdad(Crupier crupier) {
        setTitle("La edad cambio: " + crupier.getEdadCrupier());
    }

    public void inicioSesionUnJugador(Sesion sesion) {
        setTitle("Ingreso nuevo: " + sesion.getUsuario().getNombre() + " a la hora " + sesion.getFechaAcceso());
    }
    
    public void jugadorUnido(ArrayList<Jugador> jugadores){
        DefaultListModel<String> model = new DefaultListModel<>();

        for (Jugador j : jugadores) {
            String jugadorInfo = j.getNombre() + " | " + j.getSaldo();
            model.addElement(jugadorInfo);
        }

        lJugadoresUnidos.setModel(model);
    }

    public void mostrarInfo() {
        //aca tengo que mostrar toda la info.
        
        //Me tengo que traer la mesa (el crupier)
        Mesa mesa = controlador.getCrupier().getMesaAsignada();
        
        //El balance de la mesa (inicialmente cero);
        int balanceMesa  = mesa.getBalance();
        lblBalance.setText("$" + balanceMesa);
        
        //El número de ronda (inicialmente uno);
        int numeroRonda = mesa.getRondas().size();
        labelRonda.setText("Ronda #" + numeroRonda);
        
        //El número de ruleta (unívoco y asignado al crupier);
        int numeroRuleta = mesa.getId();
        labelNumeroRuleta.setText("Ruleta #" + numeroRuleta);
        
        //La lista de efectos;
        //????
        
        //La cantidad total de apuestas realizadas;
        Ronda ultimaRonda = mesa.getRondas().get(mesa.getRondas().size() - 1);
        int cantidadApuestas = ultimaRonda.getApuestas().size();
        
        //El monto total apostado;
        int montoApuestas = ultimaRonda.getTotalApuestas();
        lblApuestas.setText("Apuestas: " + cantidadApuestas + " | Monto $" + montoApuestas);
        
        //La mesa con la distribución de apuestas a cada tipo de apuesta;
        //???
        
        //La lista de los últimos lanzamientos;
        int[]ultimosLanzamientos = mesa.getUltimosLanzamientos();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (int numero : ultimosLanzamientos) {
            String numeroString = numero + ",";
            model.addElement(numeroString);
        }
        listaUltimosLanzamientos.setModel(model);
        
        //La lista de rondas efectuadas con los siguientes datos: Ronda, Saldo Balance
        //anterior al sorteo, Monto total de apuestas, Monto total de apuestas perdidas
        //(recolección), Monto total de apuestas pagadas (liquidación), Saldo Balance
        //posterior al sorteo.
        //La lista de los jugadores en la mesa y su saldo.
    }

}
